### ISSUE TITLE
Suggestion: Add Ignore URL Patterns Option

### ISSUE THREAD

**Issue by MSTEWARDSON** [1jz/WISA#17]
Hi Philip, looking at your code I feel like I could add a new feature to it to make it even better. As described in lab 4 we need to add an "ignore URL patterns" feature into other students projects. I would like to take this on with your project.

Thanks,
Matt

**Comment by 1jz** [comment]
Good work, tested everything and it worked perfectly, merged. a02c9e5

**Comment by MSTEWARDSON** [comment]
Perfect, thanks!
